print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/adn33/Desktop/Bittersweet/MainProject/Assets/Special Attacks/111/111.mb"`)
{		
	file -o "/Users/adn33/Desktop/Bittersweet/MainProject/Assets/Special Attacks/111/111.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/adn33/Desktop/Bittersweet/MainProject/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/adn33/Desktop/Bittersweet/MainProject/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/adn33/Desktop/Bittersweet/MainProject/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
